bynder_local.settings:
  type: config_object
  label: 'Bynder Local configuration'
  mapping:
    derivative:
      type: text
      label: 'The asset derivative to store locally'
    local_image_field:
      type: text
      label: 'The machine name of the field that''s used to store the image locally'